FROM golang:latest

WORKDIR ./server
COPY ./src/quote-mock ./quote-mock
COPY ./src/lib ./lib
COPY ./src/go.mod .
COPY ./src/go.sum .

RUN go mod download

RUN cd ./quote-mock && go build

EXPOSE 4443

CMD ["./quote-mock/quote-mock"]
