FROM golang:latest

WORKDIR ./server
COPY ./src/web ./web
COPY ./src/lib ./lib
COPY ./src/go.mod .
COPY ./src/go.sum .

RUN go mod download

RUN cd ./web && go build

COPY ./ssl/cert.pem ./ssl/cert.pem
COPY ./ssl/key.pem ./ssl/key.pem

EXPOSE 8080 

CMD ["./web/web"]
