FROM golang:latest

WORKDIR ./server
COPY ./src/transaction ./transaction
COPY ./src/lib ./lib
COPY ./src/go.mod .
COPY ./src/go.sum .

RUN go mod download

RUN cd ./transaction && go build

EXPOSE 5000

CMD ["./transaction/transaction"]
