version: "3"
services:
    audit:
        container_name: "audit-server"
        depends_on:
            - auditDB
        build:
            context: .
            dockerfile: docker-files/local/Dockerfile.audit
        environment:
            - ENV=DOCKER
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
    auditDB:
        image: mongo:latest
        container_name: "audit-mongodb"
        environment:
            MONGO_INITDB_DATABASE: audit
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
