version: "3"
services:
    web:
        build:
            dockerfile: docker-files/lab/Dockerfile.web
        environment:
            - ENV=LAB

    web2:
        container_name: "web-server2"
        depends_on:
            - transaction
            - audit
        build:
            context: .
            dockerfile: docker-files/lab/Dockerfile.web
        ports:
            - "8081:8080"
        environment:
            - ENV=LAB
        ulimits:
            nofile:
                soft: 65536
                hard: 65536

    transaction:
        build:
            dockerfile: docker-files/lab/Dockerfile.transaction
        environment:
            - ENV=LAB

    data:
        build:
            dockerfile: docker-files/lab/Dockerfile.data
        environment:
            - ENV=LAB

    audit:
        ports:
            - "5002:5002"
        build:
            dockerfile: docker-files/lab/Dockerfile.audit
        environment:
            - ENV=LAB
    load:
        container_name: "load-balancer"
        build:
            context: .
            dockerfile: ./loadbalancer/Dockerfile
        ports:
            - "44410:80"
