version: "3"
services:
    web:
        environment:
            - ENV=LAB
            - NAME=web2
        ports:
            - "5005:8080"
        # These limits only apply when 'docker-compose --compatibility' flag is used
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "100M"

    web2:
        environment:
            - ENV=LAB
            - NAME=web2
        ports:
            - "5006:8080"
        # These limits only apply when 'docker-compose --compatibility' flag is used
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "100M"

    transaction:
        ports:
            - "5007:5000"
        environment:
            - ENV=LAB
            - NAME=transaction

    transaction2:
        ports:
            - "5008:5000"
        environment:
            - ENV=LAB
            - NAME=transaction2

    quote-cache:
        ports:
            - "5004:5004"
        environment:
            - ENV=LAB

    audit:
        ports:
            - "5002:5002"
        build:
            dockerfile: docker-files/lab/Dockerfile.audit
        environment:
            - ENV=LAB

    load-web:
        environment:
            - ENV=LAB
        ports:
            - "8080:8080"

    load-transaction:
        environment:
            - ENV=LAB
        ports:
            - "5000:5000"
