version: "3"
services:
    web:
        build:
            context: .
            dockerfile: docker-files/lab/Dockerfile.web
        environment:
            - ENV=LAB
            - NAME=web2
        # These limits only apply when 'docker-compose --compatibility' flag is used
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "100M"

    web2:
        build:
            context: .
            dockerfile: docker-files/lab/Dockerfile.web
        environment:
            - ENV=LAB
            - NAME=web2
        # These limits only apply when 'docker-compose --compatibility' flag is used
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "100M"

    transaction:
        build:
            context: .
            dockerfile: docker-files/lab/Dockerfile.transaction
        environment:
            - ENV=LAB
            - NAME=transaction

    transaction2:
        build:
            context: .
            dockerfile: docker-files/lab/Dockerfile.transaction
        environment:
            - ENV=LAB
            - NAME=transaction2

    quote-cache:
        build:
            context: .
            dockerfile: docker-files/lab/Dockerfile.quote-cache
        ports:
            - "5004:5004"
        environment:
            - ENV=LAB

    audit:
        build:
            context: .
            dockerfile: docker-files/lab/Dockerfile.audit
        ports:
            - "5002:5002"
        environment:
            - ENV=LAB

    load-web:
        ports:
            - "8080:8080"

    load-transaction:
        ports:
            - "5000:5000"

    watchdog:
        build:
            context: .
            dockerfile: docker-files/lab/Dockerfile.watchdog
        environment:
            - ENV=LAB
