FROM golang:latest

WORKDIR ./server
COPY ./build/web.exe .
COPY ./src/urls.yml ./urls.yml
COPY ./src/dev_key.key ./dev_key.key

COPY ./ssl/cert.pem ./ssl/cert.pem
COPY ./ssl/key.pem ./ssl/key.pem

EXPOSE 8080 

CMD ["./web.exe"]
