FROM golang:latest

WORKDIR ./server
COPY ./src/audit ./audit
COPY ./src/lib ./lib
COPY ./src/go.mod .
COPY ./src/go.sum .

RUN go mod download

RUN cd ./audit && go build

EXPOSE 5002

CMD ["./audit/audit"]
