FROM golang:latest

WORKDIR ./server
COPY ./src/data ./data
COPY ./src/lib ./lib
COPY ./src/go.mod .
COPY ./src/go.sum .

RUN go mod download

RUN cd ./data && go build

EXPOSE 5001

CMD ["./data/data"]
